name:Sword_Skill
main:org.rintech.sword_skill.Main
version:0.1
author:tyuutorosan
description:Sword_Skill

commands:
  test:
    description: テストコマンド
    aliases: [他のコマンド名1, 他のコマンド名2]
    permission: コマンドの権限
    usage: コマンドの使い方
  コマンド名:
    description: コマンドの説明
    aliases: [他のコマンド名1, 他のコマンド名2]
    permission: コマンドの権限
    usage: |
      コマンドの使い方1行目
      2行目
      3行目...
 
permissions:
  権限名1.*:
    description: 権限の説明
    children:
      権限名1.権限名2: true
      権限名1.権限名3: true
      権限名1.権限名3.権限名4: true
  権限名1.権限名2:
    description: 権限の説明
    default: true
  権限名1.権限名3:
    description: 権限の説明
    default: true
  権限名1.権限名3.権限名4:
    description: 権限の説明
    default: op
    children:
      権限名1.権限名3: true