name: Sword_Skill
main: org.rintech.sword_skill.Main
version: 0.1
author: tyuutorosan
description: Sword_Skill

commands:
  test:
   description: testCommand.
   aliases: [T,t]
   permission: Sword_Skill.test
   usase: plugin test.
   
permissions:
  Sword_Skill.*:
    description: Gives access to test command
    default: true